trigger:
- azure-argo-GA

variables:
  imageName: fitness-app
  acrLoginServer: fitnessacr123.azurecr.io
  tag: $(Build.BuildId)

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: Docker@2
  displayName: Build and Push Image
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: Dockerfile
    containerRegistry: ACR-Service-Connection
    tags: |
      $(tag)

# Update Helm values.yaml
- script: |
    sed -i "s/tag:.*/tag: \"$(tag)\"/" helm/fitness-app/values.yaml
    git config user.email "devops@company.com"
    git config user.name "azure-devops"
    git add helm/fitness-app/values.yaml
    git commit -m "Update image tag to $(tag)"
    git push origin azure-argo-GA
  displayName: Update Helm values
