apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
      annotations:
        ad.datadoghq.com/{{ .Values.app.name }}.logs: >-
          [{"source":"nodejs","service":"{{ .Values.app.env.ddService }}"},
           {"source":"nodejs","service":"{{ .Values.app.name }}"}]
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
           - containerPort: {{ .Values.app.containerPort }}
          env:
           - name: MONGODB_URI
             value: "{{ .Values.app.mongodbUri }}"
           - name: PORT
             value: "{{ .Values.app.containerPort }}"
           - name: HOST
             value: "{{ .Values.app.host }}"
           - name: NODE_ENV
             value: "{{ .Values.app.nodeEnv }}"
           - name: DD_AGENT_HOST
             valueFrom:
               fieldRef:
                 fieldPath: status.hostIP
           - name: DD_TRACE_AGENT_PORT
             value: "{{ .Values.app.env.ddTraceAgentPort }}"
           - name: DD_ENV
             value: "{{ .Values.app.env.ddEnv }}"
           - name: DD_SERVICE
             value: "{{ .Values.app.env.ddService }}"
           - name: DD_VERSION
             value: "{{ .Values.app.env.ddVersion }}"
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}